# Generated by Django 2.1.4 on 2018-12-13 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_brewser_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
