# Generated by Django 2.1.4 on 2018-12-14 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_tag_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='subscribers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
