# Generated by Django 2.1.4 on 2018-12-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181214_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewser',
            name='picture',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.URLField(max_length=255),
        ),
    ]
